name: Deploy HTML to S3
on:push
jobs:
deploy:
runs-on: ubuntu-latest
steps: 
- name : checkout code from repo
uses: actions/checkout@v4
-name: configure AWS credentials 
usues: aws-actions/configure-aws-credentials@v4
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
aws-secret-access-kay: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
aws-region: ap-south-1
